export const products = [
  {
    id: 1,
    slug: "x-acto-compression-knife-set",
    name: "X-ACTO Compression Basic Knife Set",
    price: "$26.21",
    rating: 4.7,
    reviews: 5126,
    image: "https://m.media-amazon.com/images/I/71A1TQkSGRL._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/X-ACTO-Compression-including-Pumpkin-Carving/dp/B00JWFIKOC",
    features: ["3 knives included", "13 blades variety", "Soft carry case", "Precision cutting"],
    summary: "Versatile set for crafts and carving with easy blade change and secure storage.",
    description:
      "The X-ACTO Compression Basic Knife Set is designed for a variety of craft and professional uses. It includes three precision knives and 13 versatile blades, catering to different project needs. The easy-change blade system ensures quick swaps for seamless work, while the nylon soft compression case provides convenient storage and portability, making it ideal for pumpkin carving and other detailed crafts.",
    specs: {
      blade: "Carbon steel (13 types)",
      handle: "Aluminum and plastic",
      weight: "200g (complete set)",
      case: "Nylon soft compression",
      warranty: "1 year",
    },
  },
  {
    id: 2,
    slug: "diyself-precision-hobby-knife",
    name: "DIYSELF Precision Hobby Knife Set",
    price: "$16.99",
    rating: 4.6,
    reviews: 2890,
    image: "https://m.media-amazon.com/images/I/71XsjFCo0PL._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/DIYSELF-Precision-Architecture-Modeling-Scrapbooking/dp/B0987JPQ74",
    features: ["23 PCS set", "Aluminum handle", "Multiple blades", "For modeling and crafting"],
    summary: "Complete precision kit for architecture modeling and scrapbooking with durable blades.",
    description:
      "The DIYSELF Precision Hobby Knife Set is a comprehensive 23-piece toolkit perfect for architecture modeling, scrapbooking, and other detailed crafts. Featuring durable aluminum handles and multiple blade types, this set ensures precision and versatility. The included storage case keeps all components organized, making it a reliable choice for hobbyists and professionals alike.",
    specs: {
      blade: "High-carbon steel (multiple types)",
      handle: "Aluminum",
      weight: "250g (complete set)",
      case: "Plastic storage case",
      warranty: "1 year",
    },
  },
  {
    id: 3,
    slug: "x-acto-x3000-hobby-knife",
    name: "X-ACTO X3000 Rubber-Barrel Hobby Knife",
    price: "$12.53",
    rating: 4.3,
    reviews: 772,
    image: "https://m.media-amazon.com/images/I/615vAz4R45L._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/ELMERS-X-Acto-X3000-Knife-X3730Q/dp/B00BMQGI52",
    features: ["Rubber barrel grip", "Three #11 blades", "Anti-roll design", "Precision cuts"],
    summary: "Comfortable grip hobby knife for detailed craft work with built-in storage.",
    description:
      "The X-ACTO X3000 Rubber-Barrel Hobby Knife is designed for precision cutting in various craft materials. Its textured no-slip grip enhances comfort, while the anti-roll handle prevents accidents. With a built-in storage compartment for up to five #11 blades (three included), this knife is perfect for delicate tasks like trimming paper, plastic, or thin metal.",
    specs: {
      blade: "Carbon steel (#11)",
      handle: "Rubber-coated aluminum",
      weight: "40g",
      length: "14cm",
      warranty: "1 year",
    },
  },
  {
    id: 4,
    slug: "multi-angle-miter-cutter",
    name: "Multi Angle Miter Cutter",
    price: "$19.95",
    rating: 4.7,
    reviews: 1965,
    image: "https://m.media-amazon.com/images/I/61sXv5ygqlL._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/Degrees-Stainless-Plumbers-Electricians-Carpenters/dp/B07H3DDLGG",
    features: ["45-135 degree cuts", "Stainless steel blade", "Rubber handle", "Safety lock"],
    summary: "Versatile cutter for trim, chamfer, and quarter round with precise angles.",
    description:
      "The Multi Angle Miter Cutter is a multipurpose tool designed for precise 45-135 degree cuts on materials like wood, trim, and vinyl. Its stainless steel blade ensures durability, while the ergonomic rubber handle and safety lock provide comfort and safety. Ideal for plumbers, electricians, and carpenters, this cutter simplifies angle cutting with a built-in protractor for accuracy.",
    specs: {
      blade: "Stainless steel",
      handle: "Rubber grip",
      weight: "300g",
      length: "20cm",
      warranty: "1 year",
    },
  },
  {
    id: 5,
    slug: "headley-rotary-cutter-set",
    name: "Headley Tools Rotary Cutter Set",
    price: "$29.99",
    rating: 4.6,
    reviews: 1243,
    image: "https://m.media-amazon.com/images/I/71YAVIqbp4L._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/Headley-Tools-Rotary-Cutter-Set/dp/B0B58LXB24",
    features: ["45mm rotary blade", "Self-healing mat", "Acrylic ruler", "Safety lock"],
    summary: "Complete rotary cutting kit for fabric, quilting, and crafts with essential tools.",
    description:
      "The Headley Tools Rotary Cutter Set is a comprehensive kit for fabric, quilting, and craft projects. Featuring a 45mm rotary blade, self-healing cutting mat, and acrylic ruler, this set ensures smooth, precise cuts. The safety lock enhances user safety, while the ergonomic design provides comfort during extended use, making it a favorite for quilters and crafters.",
    specs: {
      blade: "Tungsten steel (45mm rotary)",
      handle: "Ergonomic plastic",
      weight: "400g (complete set)",
      case: "Plastic storage",
      warranty: "2 years",
    },
  },
  {
    id: 6,
    slug: "amazon-basics-precision-hobby-knife",
    name: "Amazon Basics Precision Hobby Knife Set",
    price: "$9.99",
    rating: 4.6,
    reviews: 5189,
    image: "https://m.media-amazon.com/images/I/71xNga1+Q5L._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/AmazonBasics-29-Piece-Precision-Hobby-Knife/dp/B07V83Q9W8",
    features: ["29-piece set", "Alloy steel blades", "Tweezers included", "Storage case"],
    summary: "Affordable precision set for hobby crafts with multiple blade types.",
    description:
      "The Amazon Basics 29-Piece Precision Hobby Knife Set is a budget-friendly option for precise cutting, carving, and trimming. Including a modeling knife, 26 razor-sharp blades, a grindstone, and tweezers, this set handles wood, cardboard, plastic, and more. The lightweight aluminum handle with a slip-free rubber grip ensures control, and the plastic storage case keeps everything organized.",
    specs: {
      blade: "Alloy steel (multiple types)",
      handle: "Aluminum with rubber grip",
      weight: "300g (complete set)",
      case: "Plastic storage case",
      warranty: "1 year",
    },
  },
  {
    id: 7,
    slug: "internets-best-premium-utility-knife",
    name: "INTERNET'S BEST Premium Utility Knife Set",
    price: "$22.99",
    rating: 4.6,
    reviews: 4066,
    image: "https://m.media-amazon.com/images/I/71jitj8Rl5L._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/Internets-Best-Premium-Utility-Retractable/dp/B01M27QHE2",
    features: ["2 retractable knives", "100 blades", "Rubber handle", "Heavy-duty cutting"],
    summary: "Durable utility knives for cardboard, carpet, and general cutting tasks.",
    description:
      "The INTERNET'S BEST Premium Utility Knife Set is built for heavy-duty cutting tasks like cardboard, carpet, and plastic. This set includes two retractable knives with rubber handles for comfort and 100 replacement blades for long-term use. The sturdy construction and easy blade replacement make it a reliable choice for professionals and DIY enthusiasts tackling tough materials.",
    specs: {
      blade: "Carbon steel (100 blades)",
      handle: "Rubber-coated metal",
      weight: "350g (complete set)",
      case: "Plastic storage",
      warranty: "1 year",
    },
  },
  {
    id: 8,
    slug: "paudin-kitchen-utility-knife",
    name: "PAUDIN Kitchen Utility Knife",
    price: "$15.99",
    rating: 4.7,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71xvLD9m9mL._AC_SX679_.jpg",
    amazonUrl: "https://www.amazon.com/PAUDIN-Kitchen-Stainless-Ergonomic-Pakkawood/dp/B09MVWT85R",
    features: ["5 inch blade", "Stainless steel", "Ergonomic pakkawood handle", "Multi-purpose"],
    summary: "Versatile kitchen knife for precise cutting with comfortable grip.",
    description:
      "The PAUDIN Kitchen Utility Knife is a versatile 5-inch knife crafted from high-quality stainless steel, perfect for slicing, dicing, and chopping in the kitchen. Its ergonomic pakkawood handle provides a comfortable, secure grip, ensuring precision and safety during use. This multi-purpose knife is ideal for both home cooks and professional chefs seeking reliability and performance.",
    specs: {
      blade: "Stainless steel (5 inch)",
      handle: "Pakkawood",
      weight: "120g",
      length: "25cm",
      warranty: "2 years",
    },
  },
  {
    id: 9,
    slug: "vivosun-gardening-hand-pruner",
    name: "VIVOSUN Gardening Hand Pruner",
    price: "$24.99",
    rating: 4.5,
    reviews: 1567,
    image: "https://m.media-amazon.com/images/I/61IoQS+EgTL._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg",
    amazonUrl: "https://www.amazon.com/VIVOSUN-12-Pack-Gardening-Straight-Stailess/dp/B085NGVT5H",
    features: ["12-pack", "Straight stainless steel", "Precision cutting", "For gardening"],
    summary: "Bulk pack of precision pruners for gardening and plant trimming.",
    description:
      "The VIVOSUN Gardening Hand Pruner set includes 12 straight stainless steel pruners designed for precision trimming in gardening tasks. Perfect for pruning plants, flowers, and small branches, these durable pruners offer sharp, clean cuts. Their lightweight design and comfortable grip make them ideal for extended use in gardens or greenhouses.",
    specs: {
      blade: "Stainless steel",
      handle: "Plastic with rubber grip",
      weight: "80g (per pruner)",
      length: "16cm",
      warranty: "1 year",
    },
  },
]

export const customerReviews = [
  {
    name: "Sarah Mitchell",
    rating: 5,
    date: "2 weeks ago",
    comment: "Absolutely incredible precision! This knife has transformed my work quality.",
  },
  {
    name: "James Chen",
    rating: 5,
    date: "1 month ago",
    comment: "Best investment I've made for my craft. The build quality is outstanding.",
  },
  {
    name: "Emily Rodriguez",
    rating: 4,
    date: "3 weeks ago",
    comment: "Great product overall. Slightly pricey but worth it for the quality.",
  },
]
